sudo: required

language: go

go:
    - 1.7

addons:
    apt:
      packages:
        - gcc-4.8
        - g++-4.8
        - libopencv-dev
        - libatlas-base-dev
    
before_install:
    - source travis/env.sh

install:
    # dep
    - travis/install.sh

script:
    - go build ./examples/flowers/predict.go

