language: go

go:
    - 1.5
    - 1.6
    - 1.7
    - tip


env:
    - MXNET=/root/MXNet

install:
    # copy
    - mkdir -p /usr/local/lib/pkgconfig/
    - cp tools/mxnet.pc /usr/local/lib/pkgconfig/
    # dep for mxnet
    - mkdir -p $MXNET
    - cd $MXNET && git clone https://github.com/dmlc/mxnet.git --recursive
    - cd $MXNET/mxnet && make -j2
    - ln -s $MXNET/mxnet/lib/libmxnet.so /usr/local/lib/libmxnet.so
    # dep for example
    - go get github.com/anthonynsimon/bild
    - go get github.com/songtianyi/go-mxnet-predictor

script:
    - go build ./examples/flowers/predict.go

